let cssQueDB = [
      {
          question: " An event in the probability that will never be happened is called as -",
          a: "Impossible event",
          b: "sure event",
          c: "Possiable event",
          d: "All of the above",
          ans: "ans1",
      },
      {
          question: "What will be the value of P(not E) if P(E) = 0.07?",
          a: "90",
          b: "007",
          c: "93",
          d: "72",
          ans: "ans3",
      },
      {
          question: "What will be the probability of getting odd numbers if a dice is thrown?" ,
          a: "1/4",
          b: "1/2",
          c: "4/2",
          d: "2",
          ans: "ans2",
      },
      {
          question:  "What is the probability of getting a sum as 3 if a dice is thrown?",
          a: "2/18",
          b: " 1/36",
          c: " 4",
          d: "1/18 ",
          ans: "ans4",
      },
      {
          question:  " What is the probability of getting an even number when a dice is thrown?",
          a: "1/6",
          b: "1/3",
          c: "2/4",
          d: "1/2",
          ans: "ans4",
      },
      {
          question:  "The probability of getting two tails when two coins are tossed is -" ,
          a: "1/4",
          b: "1/3",
          c: "1/6",
          d: "All of the above",
          ans: "ans1",
      },
      {
          question:  "What is the probability of getting the sum as a prime number if two dice are thrown?",
          a: "5/24",
          b: "5/12",
          c: "5/30",
          d: "1/4",
          ans: "ans2",
      },
      {
          question: "What is the probability of getting atleast one head if three unbiased coins are tossed?",
          a: "8/9",
          b: "1/2",
          c: "5/8",
          d: "7/8",
          ans: "ans4",
      },
      {
          question: "What is the probability of getting 1 and 5 if a dice is thrown once?",
          a: "1/3",
          b: "1/6",
          c: "2/3",
          d: "All of the above",
          ans: "ans1",
      },
      {
          question: "What will be the probability of losing a game if the winning probability is 0.3?",
          a: "0.7",
          b: "0.8",
          c: "0.5",
          d: "0.6",
          ans: "ans1",
      }
  ];
  
  
  
  let htmlQueDB = [
      {
          question: " Pipe A can fill in 16 minutes and pipe B empties it in 24 minutes.If both pipes are opened together, after how many minutes should B is closed,so that the tank is filled in 30 minutes?",
          a: "18 min" ,
          b: "20 min",
          c: "21 min",
          d: "15 min",
          ans: "ans3",
      },
      {
          question: "One pipe can fill tank three times as fast as another pipe.If together the two pipes can fill the tank in 36 minutes,the the slower pipe alone will be able to fill the tank in",
          a: "144 min",
          b: "140 min",
          c: "136 min",
          d: "132 min ",
          ans: "ans1",
      },
      {
          question: "Two pipes A & B can fill a cistern in 24 minues and 36 minutes respectively.If both the pipes are opened together, after how much time B should be closed so that the tank is full in 20 minutes?" ,
          a: "5 min",
          b: "9 min",
          c: "6 min",
          d: "11 min",
          ans: "ans3",
      },
      {
          question: "Two inlet pipes A and B together can fill a tank in 24 min, and it takes 6 min more when one leak is developed in the tank.Find the time taken by leak alone to empty the tank.",
          a: "2 hr",
          b: "4 hr",
          c: "2.5 hr ",
          d: "3 hr",
          ans: "ans1",
      },
      {
          question: "Two pipes A and B together can fill a Tank in 6 hours.If pipe A can fill 5 hours faster than pipe B,in how many hours pipe B alone can fill the tank?",
          a: "12",
          b: "10",
          c: "18",
          d: "15",
          ans: "ans4",
      },
      {
          question: "A tap can fill in 8 hrs.After half the tank is filled,three more similar taps are opened.What is the total time taken to fill the tank completely?",
          a: "6 hrs",
          b: "5 hrs",       
          c: "4 hrs",
          d: "2 hrs",
          ans: "ans2",
      },
      {
          question:  "Pipe X and Z can filled a tank in 18 hours and in 4 hours.If pipe X is opened at 9:00 am and pipe Z is opened at 4:00 pm,then at what time will tank be filled.",
          a: "6:00 pm",
          b: "4:00 pm",
          c: "5:00 am ",
          d: "9:00 am",
          ans: "ans1",
      },
      {
          question: "Pipes A and B can fill a tank in 5 and 6 hours respectively. Pipe C can empty it in 12 hours. If all the three pipes are opened together, then the tank will be filled in:",
          a: "3 9/17 hrs",
          b: "1 13/17 hrs",
          c: "2 8/11 hrs",
          d: "4 1/2 hrs",
          ans: "ans1",
      },
      {
          question: "Two pipes A and B can fill a tank in 20 and 30 minutes respectively. If both the pipes are used together, then how long it will take to fill the tank?" ,
          a: "10 min",
          b: "20 min",
          c: "15 min",
          d: "12 min",
          ans: "ans4",
      },
      {
          question:  "Pipe A can fill a tank in 45 hrs and pipe B can fill it in 36 hrs. If both the pipes are opened in the empty tank. In how many hours will it be full?",
          a: "10 hr",
          b: "15 hr",
          c: "28 hr",
          d: "20 hr",
          ans: "ans4",  
      }
      
  ];
  
  let jsQueDB = [
      {
          question: "The sum of ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?" ,
          a: "8 years",
          b: "4 years",
          c: "10 years",
          d: "None of the above",
          ans: "ans2",
      },
      {
          question: "A is two years older than B who is twice as old as C. If the total of the ages of A, B and C be 27, then how old is B?",
          a: "10",
          b: "8",
          c: "6",
          d: "7",
          ans: "ans1",
      },
      {
          question: "Present ages of Sameer and Anand are in the ratio of 5 : 4 respectively. Three years hence, the ratio of their ages will become 11 : 9 respectively. What is Anand's present age in years?",
          a: "27",
          b: "24",
          c: "40",
          d: " None of the Above",
          ans: "ans2",
      },
      {
          question: "Raju age after 15 years will be 5 times his age 5 years back, What is the present age of Raju",
          a: "15",
          b: "10",
          c: "14",
          d: "8",
          ans: "ans2",
      },
      {question: "Sachin is younger than Rahul by 7 years. If the ratio of their ages is 7:9, find the age of Sachin" ,
          a: "23.5",
          b: "14.5",
          c: "12.5",
          d: "16.5",
          ans: "ans2",
      },
      {
          question: "The total age of A and B is 12 years more than the total age of B and C. C is how many year younger than A",
          a: "11",
          b: "12",
          c: "13",
          d: "14",
          ans: "ans2",
      },
      {
          question: "Ram and Shyam’s average age is 65 years. The average age of Ram, Shyam and John is 53 years. What is the age of John?",
          a: "29 years",
          b: "31 years",
          c: "59 years",
          d: "45 years",
          ans: "ans1",
      },
      {
          question:  "The present ages of Aman and Nina are 59 and 37 years, respectively. What was the ratio of the ages of Nina and Aman 13 years ago?",
          a: "3:2",
          b: "46:25",
          c: "12:23",
          d: "8:3",
          ans: "ans3",
      },
      {
          question: "Ramesh's age after 16 years will be 5 times his age 4 years back. What is the present age of Ramesh?",
          a: "14 years",
          b: "9 years",
          c: "16 years",
          d: "21 years",
          ans: "ans2",
      },
      {
          question:  " The sum of the ages of 4 children born at the intervals of the 3 years each is 58 years. What is the age of the youngest child?",
          a: "10 years",
          b: "4 years",
          c: "8 years",
          d: "6 years",
          ans: "ans1",
      }
  ];
  
  
  let pythonQueDB = [
      {
          question: "A person sold a stove for Rs. 423 and incurred a loss of 6%. At what price would it be sold so as to earn a profit of 8%?" ,
          a: "525",
          b: "500",
          c: "486",
          d: "490",
          ans: "ans3",
      },
      {
          question: "A fruit seller buys lemons at 2 for a rupee and sells then at 5 for three rupees. His gain percent is",
          a: "10%",
          b: "20%",
          c: "25%",
          d: "15%",
          ans: "ans2",
      },
      {
          question: "A sells a car to B at 10% loss. If B sells it for Rs. 54000 and gains 20%, the cost price of the car for A was" ,
          a: "50000",
          b: "25000",
          c: "37000",
          d: "60000",
          ans: "ans1",
      },
      {
          question:  "If selling price of 40 articles is equal to cost price of 50 articles, the loss or gain percent is",
          a: "25% loss",
          b: "25% gain",
          c: "20% loss",
          d: "20% gain",
          ans: "ans2",
      },
      {
          question: "The ratio of cost price and selling price is 4:5. The profit percent is",
          a: "10%",
          b: "20%",
          c: "25%",
          d: "30%",
          ans: "ans3",
      },
      {
          question:  "If a person sells a ‘sari’ for Rs. 5200, making a profit of 30%, then the cost price of the sari is" ,
          a: "Rs. 4420",
          b: "Rs. 4000",
          c: "Rs. 3900",
          d: "Rs. 2500",
          ans: "ans2",
      },
      {
          question: "A shopkeeper earns a profit of 15% after selling a book at 20% discount on the printed price. The ratio of the cost price and printed price of the book is?",
          a: "20:23",
          b: "23:22",
          c: "23:16",
          d: "16:23",
          ans: "ans4",
      },
      {
          question:  "Rambabu sells paper planes at the rate of 20 planes for Re. 1. If he gets profit of 20%, how many planes did he buy in 1 rupee?",
          a: "16",
          b: "40",
          c: "24",
          d: "All of the above",
          ans: "ans3",
      },
      {
          question: "A cheater manipulated his weighing machine so that it shows 1kg for 970 grams. How much profit does he get?",
          a:  "397/100%",
          b: "0.3 %",
          c: "300/97 %",
          d: "0.03 %",
          ans: "ans3",
      },
      {
          question: "Ajay incurred loss of 20% by selling a vase for Rs. 2880. To get a profit of 20% at what price should he sell the vase?",
          a: "5760",
          b:  "4320",
          c:  "1440",
          d: "3500",
          ans: "ans2",
      }
  ];
  Footer